---
- name: Check if the FS is already created an ready to use
  stat:
    path: "/app/{{ disk }}/data/.donoterase"
  register: fs_ready

- name: Check if disk is present with fdisk
  shell: fdisk -l /dev/{{ disk }}
  when: fs_ready.stat.exists == False

- name: Create PV if none is present
  shell: pvs /dev/{{ disk }} || pvcreate /dev/{{ disk }}
  when: fs_ready.stat.exists == False

- name: Create VG if none is present
  shell: vgs vg_{{ disk }} || vgcreate vg_{{ disk }} /dev/{{ disk }}
  when: fs_ready.stat.exists == False

- name: Create LV if none is present
  shell: lvs /dev/vg_{{ disk }}/lv_kafka || lvcreate vg_{{ disk }} --name=lv_kafka -l 100%FREE
  when: fs_ready.stat.exists == False

- name: Create XFS filesystem if none is present
  filesystem:
    fstype: xfs
    dev: "/dev/mapper/vg_{{ disk }}-lv_kafka"
    resizefs: no
    force: no
  when: fs_ready.stat.exists == False

- name: Create the Mountpoint on the server (/app/sdX)
  file:
    path: "/app/{{ disk }}"
    state: directory
    mode: '0755'
  when: fs_ready.stat.exists == False

- name: Mount the partition and add en entry to FSTab
  mount:
    src: "/dev/mapper/vg_{{ disk }}-lv_kafka"
    path: "/app/{{ item }}"
    state: mounted
    fstype: xfs
    backup: yes
    dump: "0"
    passno: "2"
  when: fs_ready.stat.exists == False

- name: Create the directory /app/sdX/data
  file:
    path: "/app/{{ disk }}/data"
    state: directory
  when: fs_ready.stat.exists == False

- name: Create the file /app/sdX/data/.donoterase
  file:
    path: "/mount/{{ disk }}/data/.donoterase"
    state: file
  when: fs_ready.stat.exists == False
