---
- name: PCC - LVM - Check if disk /dev/sda is mentioned
  fail:
    msg: "THe SDA Disk mustn't be used for Kafka data storage, remove it from the list and relaunch the Playbook"
  when: disk == 'sda'

- name: Check if the FS is already created an ready to use
  stat:
    path: "/mount/{{ disk }}/data/.ready"
  register: fs_ready

- name: PCC - LVM - Check if disk is present with fdisk
  shell: fdisk -l /dev/{{ disk }}
  when: fs_ready.stat.exists == False

- name: PCC - LVM - Create PV if none is present
  shell: pvs /dev/{{ disk }} || pvcreate /dev/{{ disk }}
  when: fs_ready.stat.exists == False

- name: PCC - LVM - Create VG if none is present
  shell: vgs vg_{{ disk }} || vgcreate vg_{{ disk }} /dev/{{ disk }}
  when: fs_ready.stat.exists == False

- name: PCC - LVM - Create LV if none is present
  shell: lvs /dev/vg_{{ disk }}/lv_kafka || lvcreate vg_{{ disk }} --name=lv_kafka -l 100%FREE
  when: fs_ready.stat.exists == False

- name: PCC - LVM - Create XFS filesystem if none is present
  filesystem:
    fstype: xfs
    dev: "/dev/mapper/vg_{{ disk }}-lv_kafka"
    resizefs: no
    force: no
  when: fs_ready.stat.exists == False

- name: PCC - LVM - Create the Mountpoint on the server (/mount/sdX)
  file:
    path: "/mount/{{ disk }}"
    state: directory
    mode: '0755'
  when: fs_ready.stat.exists == False

- name: PCC - LVM - Mount the partition andd add en entry to FSTab
  mount:
    src: "/dev/mapper/vg_{{ disk }}-lv_kafka"
    path: "/mount/{{ item }}"
    state: mounted
    fstype: xfs
    backup: yes
    dump: "0"
    passno: "2"
  when: fs_ready.stat.exists == False

- name: PCC - LVM - Create the directory /mount/sdX/data
  file:
    path: "/mount/{{ disk }}/data"
    state: directory
  when: fs_ready.stat.exists == False

- name: PCC - LVM - Create the file /mount/sdX/data/.ready
  file:
    path: "/mount/{{ disk }}/data/.ready"
    state: file
  when: fs_ready.stat.exists == False
