---
- hosts: all
  gather_facts: yes
  vars:
    data_disks:
      - sda
      - sdb
      - sdN
  tasks:
  - name: Launching the role for each disk
    include_role:
      name: initialization
    vars:
      disk: "{{ item }}"
    with_items: "{{ data_disks }}"
