---

- name: Remove all traces of legacy Docker (provided by the OS repos)
  apt:
    autoremove: yes
    autoclean: yes
    state: absent
    name:
     - docker 
     - docker-engine 
     - docker.io 
     - containerd 
     - runc

- name: Install required packages for Docker-ce
  apt:
    update_cache: yes
    state: present
    name:
     - apt-transport-https
     - ca-certificates
     - curl
     - gnupg-agent
     - software-properties-common

- name: Add key for Docker ce Repo
  apt_key:
    state: present
    url: https://download.docker.com/linux/debian/gpg
    keyring: /etc/apt/trusted.gpg.d/docker.gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- name: Add Docker CE repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
    state: present
    filename: docker

- name: Install Docker CE engine and PIP3 (required for docker-compose)
  apt:
    update_cache: yes
    state: present
    name:
      - docker-ce={{ docker_engine_version }}
      - python3-pip

- name: Install docker-compose
  pip:
    executable: pip3
    name: docker-compose=={{ docker_compose_version }}
    state: present
